#------------------------------------------------------------------#
# must check the direction of data_root and result_root before run #
#------------------------------------------------------------------#

#configure feature path
# **** please must modify the data_root before first running ****
data_root: &d_r ./data/data
#modelnet40_ft: !join [*d_r, ModelNet40_mvcnn_gvcnn.mat]
#ntu2012_ft: !join [*d_r, NTU2012_mvcnn_gvcnn.mat]
data_fault1: !join [*d_r, fault1.csv]
data_fault2: !join [*d_r, fault2.csv]
data_fault3: !join [*d_r, fault3.csv]
data_normal: !join [*d_r, normal.csv]
data_fault4&fault2: !join [*d_r, 2021_59.csv]
data_fault4&fault1: !join [*d_r, 2021_60.csv]
data_fault3&fault1: !join [*d_r, 2021_61.csv]


#Hypergraph
graph_type: &g_t hypergraph
K_neigs: [15]
#K_neigs: [10, 15 ]
m_prob: 1
is_probH: False
#---------------------------------------
# change me
use_mvcnn_feature_for_structure: False
use_gvcnn_feature_for_structure: False
#---------------------------------------


#Model
#--------------------------------------------------
# select the dataset you use, ModelNet40 or NTU2012
on_dataset: &o_d data
#on_dataset: &o_d ModelNet40
#on_dataset: &o_d NTU2012
#--------------------------------------------------

#---------------------------------------
# change me
use_mvcnn_feature: False
use_gvcnn_feature: False
#---------------------------------------


#Result
# configure result path
# **** please must modify the result_root before first running ****
result_root: &r_r ./result
result_sub_folder: !join [*r_r, !concat [ *g_t, _, *o_d ]]
ckpt_folder: !join [*r_r, ckpt]


#Train
max_epoch: 200
n_hid: 64
lr: 0.01
milestones: [100]
gamma: 0.9
drop_out: 0.5
print_freq: 100
weight_decay: 0.0005
decay_step: 200
decay_rate: 0.7